INSERT INTO `countries` (`id`, `fips`, `iso`, `domain`, `en_name`, `fa_name`, `status`, `created_at`, `updated_at`) VALUES
(1, 'AA', 'AW', '.aw', 'Aruba', 'آروبا', 1, NULL, NULL),
(2, 'AC', 'AG', '.ag', 'Antigua and Barbuda', 'آنتیگوا و باربودا', 1, NULL, '2024-04-27 11:50:19'),
(3, 'AE', 'AE', '.ae', 'United Arab Emirates', 'امارات متحده عربی', 1, NULL, NULL),
(4, 'AF', 'AF', '.af', 'Afghanistan', 'افغانستان', 1, NULL, NULL),
(5, 'AG', 'DZ', '.dz', 'Algeria', 'الجزایر', 1, NULL, NULL),
(6, 'AJ', 'AZ', '.az', 'Azerbaijan', 'آذربایجان', 1, NULL, NULL),
(7, 'AL', 'AL', '.al', 'Albania', 'آلبانی', 1, NULL, NULL),
(8, 'AM', 'AM', '.am', 'Armenia', 'ارمنستان', 1, NULL, NULL),
(9, 'AN', 'AD', '.ad', 'Andorra', 'آندورا', 1, NULL, NULL),
(10, 'AO', 'AO', '.ao', 'Angola', 'آنگولا', 1, NULL, NULL),
(11, 'AQ', 'AS', '.as', 'American Samoa', 'ساموای آمریکایی', 1, NULL, NULL),
(12, 'AR', 'AR', '.ar', 'Argentina', 'آرژانتین', 1, NULL, NULL),
(13, 'AS', 'AU', '.au', 'Australia', 'استرالیا', 1, NULL, NULL),
(14, 'AT', '-', '-', 'Ashmore and Cartier Islands', 'اشکمور و جزایر کارتیه', 1, NULL, NULL),
(15, 'AU', 'AT', '.at', 'Austria', 'اتریش', 1, NULL, NULL),
(16, 'AV', 'AI', '.ai', 'Anguilla', 'آنگویلا', 1, NULL, NULL),
(17, 'AX', 'AX', '.ax', 'Åland Islands', 'جزایر الند', 1, NULL, NULL),
(18, 'AY', 'AQ', '.aq', 'Antarctica', 'قطب جنوب', 1, NULL, NULL),
(19, 'BA', 'BH', '.bh', 'Bahrain', 'بحرین', 1, NULL, NULL),
(20, 'BB', 'BB', '.bb', 'Barbados', 'باربادوس', 1, NULL, NULL),
(21, 'BC', 'BW', '.bw', 'Botswana', 'بوتسوانا', 1, NULL, NULL),
(22, 'BD', 'BM', '.bm', 'Bermuda', 'برمودا', 1, NULL, NULL),
(23, 'BE', 'BE', '.be', 'Belgium', 'بلژیک', 1, NULL, NULL),
(24, 'BF', 'BS', '.bs', 'Bahamas, The', 'باهاما، The', 1, NULL, NULL),
(25, 'BG', 'BD', '.bd', 'Bangladesh', 'بنگلادش', 1, NULL, NULL),
(26, 'BH', 'BZ', '.bz', 'Belize', 'بلیز', 1, NULL, NULL),
(27, 'BK', 'BA', '.ba', 'Bosnia and Herzegovina', 'بوسنی و هرزگوین', 1, NULL, NULL),
(28, 'BL', 'BO', '.bo', 'Bolivia', 'بولیوی', 1, NULL, NULL),
(29, 'BM', 'MM', '.mm', 'Myanmar', 'میانمار', 1, NULL, NULL),
(30, 'BN', 'BJ', '.bj', 'Benin', 'بنین', 1, NULL, NULL),
(31, 'BO', 'BY', '.by', 'Belarus', 'بلاروس', 1, NULL, NULL),
(32, 'BP', 'SB', '.sb', 'Solomon Islands', 'جزایر سلیمان', 1, NULL, NULL),
(33, 'BQ', '-', '-', 'Navassa Island', 'جزیره ناواسا', 1, NULL, NULL),
(34, 'BR', 'BR', '.br', 'Brazil', 'برزیل', 1, NULL, NULL),
(35, 'BS', '-', '-', 'Bassas da India', 'باساس دا هند', 1, NULL, NULL),
(36, 'BT', 'BT', '.bt', 'Bhutan', 'بوتان', 1, NULL, NULL),
(37, 'BU', 'BG', '.bg', 'Bulgaria', 'بلغارستان', 1, NULL, NULL),
(38, 'BV', 'BV', '.bv', 'Bouvet Island', 'جزیره Bouvet', 1, NULL, NULL),
(39, 'BX', 'BN', '.bn', 'Brunei', 'برونئی', 1, NULL, NULL),
(40, 'BY', 'BI', '.bi', 'Burundi', 'بوروندی', 1, NULL, NULL),
(41, 'CA', 'CA', '.ca', 'Canada', 'کانادا', 1, NULL, NULL),
(42, 'CB', 'KH', '.kh', 'Cambodia', 'کامبوج', 1, NULL, NULL),
(43, 'CD', 'TD', '.td', 'Chad', 'چاد', 1, NULL, NULL),
(44, 'CE', 'LK', '.lk', 'Sri Lanka', 'سری لانکا', 1, NULL, NULL),
(45, 'CF', 'CG', '.cg', 'Congo, Republic of the', 'کنگو، جمهوری', 1, NULL, NULL),
(46, 'CG', 'CD', '.cd', 'Congo, Democratic Republic of the', 'کنگو، جمهوری دموکراتیک', 1, NULL, NULL),
(47, 'CH', 'CN', '.cn', 'China', 'چين', 1, NULL, NULL),
(48, 'CI', 'CL', '.cl', 'Chile', 'شیلی', 1, NULL, NULL),
(49, 'CJ', 'KY', '.ky', 'Cayman Islands', 'جزایر کیمن', 1, NULL, NULL),
(50, 'CK', 'CC', '.cc', 'Cocos (Keeling) Islands', 'جزایر کوکوس (کایلینگ)', 1, NULL, NULL),
(51, 'CM', 'CM', '.cm', 'Cameroon', 'کامرون', 1, NULL, NULL),
(52, 'CN', 'KM', '.km', 'Comoros', 'کومور', 1, NULL, NULL),
(53, 'CO', 'CO', '.co', 'Colombia', 'کلمبیا', 1, NULL, NULL),
(54, 'CQ', 'MP', '.mp', 'Northern Mariana Islands', 'جزایر ماریانای شمالی', 1, NULL, NULL),
(55, 'CR', '-', '-', 'Coral Sea Islands', 'جزایر دریای مرجانی', 1, NULL, NULL),
(56, 'CS', 'CR', '.cr', 'Costa Rica', 'کاستاریکا', 1, NULL, NULL),
(57, 'CT', 'CF', '.cf', 'Central African Republic', 'جمهوری آفریقای مرکزی', 1, NULL, NULL),
(58, 'CU', 'CU', '.cu', 'Cuba', 'کوبا', 1, NULL, NULL),
(59, 'CV', 'CV', '.cv', 'Cape Verde', 'کیپ ورد', 1, NULL, NULL),
(60, 'CW', 'CK', '.ck', 'Cook Islands', 'جزایر کوک', 1, NULL, NULL),
(61, 'CY', 'CY', '.cy', 'Cyprus', 'قبرس', 1, NULL, NULL),
(62, 'DA', 'DK', '.dk', 'Denmark', 'دانمارک', 1, NULL, NULL),
(63, 'DJ', 'DJ', '.dj', 'Djibouti', 'جیبوتی', 1, NULL, NULL),
(64, 'DO', 'DM', '.dm', 'Dominica', 'دومینیکا', 1, NULL, NULL),
(65, 'DQ', 'UM', '-', 'Jarvis Island', 'جزیره جارویس', 1, NULL, NULL),
(66, 'DR', 'DO', '.do', 'Dominican Republic', 'جمهوری دومینیکن', 1, NULL, NULL),
(67, 'DX', '-', '-', 'Dhekelia Sovereign Base Area', 'منطقه ممنوعه Dhekelia', 1, NULL, NULL),
(68, 'EC', 'EC', '.ec', 'Ecuador', 'اکوادور', 1, NULL, NULL),
(69, 'EG', 'EG', '.eg', 'Egypt', 'مصر', 1, NULL, NULL),
(70, 'EI', 'IE', '.ie', 'Ireland', 'ایرلند', 1, NULL, NULL),
(71, 'EK', 'GQ', '.gq', 'Equatorial Guinea', 'گینه استوایی', 1, NULL, NULL),
(72, 'EN', 'EE', '.ee', 'Estonia', 'استونی', 1, NULL, NULL),
(73, 'ER', 'ER', '.er', 'Eritrea', 'اریتره', 1, NULL, NULL),
(74, 'ES', 'SV', '.sv', 'El Salvador', 'السالوادور', 1, NULL, NULL),
(75, 'ET', 'ET', '.et', 'Ethiopia', 'اتیوپی', 1, NULL, NULL),
(76, 'EU', '-', '-', 'Europa Island', 'جزیره اروپا', 1, NULL, NULL),
(77, 'EZ', 'CZ', '.cz', 'Czech Republic', 'جمهوری چک', 1, NULL, NULL),
(78, 'FG', 'GF', '.gf', 'French Guiana', 'گویان فرانسه', 1, NULL, NULL),
(79, 'FI', 'FI', '.fi', 'Finland', 'فنلاند', 1, NULL, NULL),
(80, 'FJ', 'FJ', '.fj', 'Fiji', 'فیجی', 1, NULL, NULL),
(81, 'FK', 'FK', '.fk', 'Falkland Islands (Islas Malvinas)', 'جزایر فالکلند (جزایر مالویناس)', 1, NULL, NULL),
(82, 'FM', 'FM', '.fm', 'Micronesia, Federated States of', 'میکرونزی، ایالات فدرال', 1, NULL, NULL),
(83, 'FO', 'FO', '.fo', 'Faroe Islands', 'جزایر فارو', 1, NULL, NULL),
(84, 'FP', 'PF', '.pf', 'French Polynesia', 'پلینزی فرانسه', 1, NULL, NULL),
(85, 'FQ', 'UM', '-', 'Baker Island', 'جزیره بیکر', 1, NULL, NULL),
(86, 'FR', 'FR', '.fr', 'France', 'فرانسه', 1, NULL, NULL),
(87, 'FS', 'TF', '.tf', 'French Southern and Antarctic Lands', 'زمینهای جنوب و جنوب قطب جنوب فرانسه', 1, NULL, NULL),
(88, 'GA', 'GM', '.gm', 'Gambia, The', 'گامبیا، The', 1, NULL, NULL),
(89, 'GB', 'GA', '.ga', 'Gabon', 'گابن', 1, NULL, NULL),
(90, 'GG', 'GE', '.ge', 'Georgia', 'جورجیا', 1, NULL, NULL),
(91, 'GH', 'GH', '.gh', 'Ghana', 'غنا', 1, NULL, NULL),
(92, 'GI', 'GI', '.gi', 'Gibraltar', 'جبل الطارق', 1, NULL, NULL),
(93, 'GJ', 'GD', '.gd', 'Grenada', 'گرانادا', 1, NULL, NULL),
(94, 'GK', '-', '.gg', 'Guernsey', 'گورنسی', 1, NULL, NULL),
(95, 'GL', 'GL', '.gl', 'Greenland', 'گرینلند', 1, NULL, NULL),
(96, 'GM', 'DE', '.de', 'Germany', 'آلمان', 1, NULL, NULL),
(97, 'GO', '-', '-', 'Glorioso Islands', 'جزایر گلوریوزو', 1, NULL, NULL),
(98, 'GP', 'GP', '.gp', 'Guadeloupe', 'گوادلوپ', 1, NULL, NULL),
(99, 'GQ', 'GU', '.gu', 'Guam', 'گوام', 1, NULL, NULL),
(100, 'GR', 'GR', '.gr', 'Greece', 'یونان', 1, NULL, NULL),
(101, 'GT', 'GT', '.gt', 'Guatemala', 'گواتمالا', 1, NULL, NULL),
(102, 'GV', 'GN', '.gn', 'Guinea', 'گینه', 1, NULL, NULL),
(103, 'GY', 'GY', '.gy', 'Guyana', 'گایانا', 1, NULL, NULL),
(104, 'GZ', '-', '-', 'Gaza Strip', 'نوار غزه', 1, NULL, NULL),
(105, 'HA', 'HT', '.ht', 'Haiti', 'هائیتی', 1, NULL, NULL),
(106, 'HK', 'HK', '.hk', 'Hong Kong', 'هنگ کنگ', 1, NULL, NULL),
(107, 'HM', 'HM', '.hm', 'Heard Island and McDonald Islands', 'جزایر هرد و جزایر مک دونالد', 1, NULL, NULL),
(108, 'HO', 'HN', '.hn', 'Honduras', 'هندوراس', 1, NULL, NULL),
(109, 'HQ', 'UM', '-', 'Howland Island', 'جزیره Howland', 1, NULL, NULL),
(110, 'HR', 'HR', '.hr', 'Croatia', 'کرواسی', 1, NULL, NULL),
(111, 'HU', 'HU', '.hu', 'Hungary', 'مجارستان', 1, NULL, NULL),
(112, 'IC', 'IS', '.is', 'Iceland', 'ایسلند', 1, NULL, NULL),
(113, 'ID', 'ID', '.id', 'Indonesia', 'اندونزی', 1, NULL, NULL),
(114, 'IM', 'IM', '.im', 'Isle of Man', 'جزیره من', 1, NULL, NULL),
(115, 'IN', 'IN', '.in', 'India', 'هندوستان', 1, NULL, NULL),
(116, 'IO', 'IO', '.io', 'British Indian Ocean Territory', 'قلمرو اقیانوس هند بریتانیا', 1, NULL, NULL),
(117, 'IP', '-', '-', 'Clipperton Island', 'جزیره Clipperton', 1, NULL, NULL),
(118, 'IR', 'IR', '.ir', 'Iran', 'ایران', 1, NULL, NULL),
(119, 'IS', 'IL', '.il', 'Israel', 'اسرائيل', 1, NULL, NULL),
(120, 'IT', 'IT', '.it', 'Italy', 'ایتالیا', 1, NULL, NULL),
(121, 'IV', 'CI', '.ci', 'Cote d\'Ivoire', 'ساحل عاج', 1, NULL, NULL),
(122, 'IZ', 'IQ', '.iq', 'Iraq', 'عراق', 1, NULL, NULL),
(123, 'JA', 'JP', '.jp', 'Japan', 'ژاپن', 1, NULL, NULL),
(124, 'JE', 'JE', '.je', 'Jersey', 'جرسی', 1, NULL, NULL),
(125, 'JM', 'JM', '.jm', 'Jamaica', 'جامائیکا', 1, NULL, NULL),
(126, 'JN', 'SJ', '-', 'Jan Mayen', 'Jan Mayen', 1, NULL, NULL),
(127, 'JO', 'JO', '.jo', 'Jordan', 'اردن', 1, NULL, NULL),
(128, 'JQ', 'UM', '-', 'Johnston Atoll', 'جانستون اتول', 1, NULL, NULL),
(129, 'JU', '-', '-', 'Juan de Nova Island', 'جزیره خوان جزیره نوا', 1, NULL, NULL),
(130, 'KE', 'KE', '.ke', 'Kenya', 'کنیا', 1, NULL, NULL),
(131, 'KG', 'KG', '.kg', 'Kyrgyzstan', 'قرقیزستان', 1, NULL, NULL),
(132, 'KN', 'KP', '.kp', 'Korea, North', 'کره شمالی', 1, NULL, NULL),
(133, 'KQ', 'UM', '-', 'Kingman Reef', 'کینگمن ریف', 1, NULL, NULL),
(134, 'KR', 'KI', '.ki', 'Kiribati', 'کیریباتی', 1, NULL, NULL),
(135, 'KS', 'KR', '.kr', 'Korea, South', 'کره جنوبی', 1, NULL, NULL),
(136, 'KT', 'CX', '.cx', 'Christmas Island', 'جزیره کریسمس', 1, NULL, NULL),
(137, 'KU', 'KW', '.kw', 'Kuwait', 'کویت', 1, NULL, NULL),
(138, 'KV', 'KV', '-', 'Kosovo', 'کوزوو', 1, NULL, NULL),
(139, 'KZ', 'KZ', '.kz', 'Kazakhstan', 'قزاقستان', 1, NULL, NULL),
(140, 'LA', 'LA', '.la', 'Laos', 'لائوس', 1, NULL, NULL),
(141, 'LE', 'LB', '.lb', 'Lebanon', 'لبنان', 1, NULL, NULL),
(142, 'LG', 'LV', '.lv', 'Latvia', 'لتونی', 1, NULL, NULL),
(143, 'LH', 'LT', '.lt', 'Lithuania', 'لیتوانی', 1, NULL, NULL),
(144, 'LI', 'LR', '.lr', 'Liberia', 'لیبریا', 1, NULL, NULL),
(145, 'LO', 'SK', '.sk', 'Slovakia', 'اسلواکی', 1, NULL, NULL),
(146, 'LQ', 'UM', '-', 'Palmyra Atoll', 'پالمیرا اتل', 1, NULL, NULL),
(147, 'LS', 'LI', '.li', 'Liechtenstein', 'لیختن اشتاین', 1, NULL, NULL),
(148, 'LT', 'LS', '.ls', 'Lesotho', 'لسوتو', 1, NULL, NULL),
(149, 'LU', 'LU', '.lu', 'Luxembourg', 'لوکزامبورگ', 1, NULL, NULL),
(150, 'LY', 'LY', '.ly', 'Libyan Arab', 'عرب لیبی', 1, NULL, NULL),
(151, 'MA', 'MG', '.mg', 'Madagascar', 'ماداگاسکار', 1, NULL, NULL),
(152, 'MB', 'MQ', '.mq', 'Martinique', 'مارتینیک', 1, NULL, NULL),
(153, 'MC', 'MO', '.mo', 'Macau', 'ماکائو', 1, NULL, NULL),
(154, 'MD', 'MD', '.md', 'Moldova, Republic of', 'مولداوی، جمهوری', 1, NULL, NULL),
(155, 'MF', 'YT', '.yt', 'Mayotte', 'مایوت', 1, NULL, NULL),
(156, 'MG', 'MN', '.mn', 'Mongolia', 'مغولستان', 1, NULL, NULL),
(157, 'MH', 'MS', '.ms', 'Montserrat', 'مونتسرات', 1, NULL, NULL),
(158, 'MI', 'MW', '.mw', 'Malawi', 'مالاوی', 1, NULL, NULL),
(159, 'MJ', 'ME', '.me', 'Montenegro', 'مونته نگرو', 1, NULL, NULL),
(160, 'MK', 'MK', '.mk', 'The Former Yugoslav Republic of Macedonia', 'جمهوری مقدونیه یوگسلاوی سابق', 1, NULL, NULL),
(161, 'ML', 'ML', '.ml', 'Mali', 'مالزی', 1, NULL, NULL),
(162, 'MN', 'MC', '.mc', 'Monaco', 'موناکو', 1, NULL, NULL),
(163, 'MO', 'MA', '.ma', 'Morocco', 'مراکش', 1, NULL, NULL),
(164, 'MP', 'MU', '.mu', 'Mauritius', 'موریس', 1, NULL, NULL),
(165, 'MQ', 'UM', '-', 'Midway Islands', 'جزایر میدوی', 1, NULL, NULL),
(166, 'MR', 'MR', '.mr', 'Mauritania', 'موریتانی', 1, NULL, NULL),
(167, 'MT', 'MT', '.mt', 'Malta', 'مالت', 1, NULL, NULL),
(168, 'MU', 'OM', '.om', 'Oman', 'عمان', 1, NULL, NULL),
(169, 'MV', 'MV', '.mv', 'Maldives', 'مالدیو', 1, NULL, NULL),
(170, 'MX', 'MX', '.mx', 'Mexico', 'مکزیک', 1, NULL, NULL),
(171, 'MY', 'MY', '.my', 'Malaysia', 'مالزی', 1, NULL, NULL),
(172, 'MZ', 'MZ', '.mz', 'Mozambique', 'موزامبیک', 1, NULL, NULL),
(173, 'NC', 'NC', '.nc', 'New Caledonia', 'کالدونیای جدید', 1, NULL, NULL),
(174, 'NE', 'NU', '.nu', 'Niue', 'نیو', 1, NULL, NULL),
(175, 'NF', 'NF', '.nf', 'Norfolk Island', 'جزیره نورفولک', 1, NULL, NULL),
(176, 'NG', 'NE', '.ne', 'Niger', 'نیجر', 1, NULL, NULL),
(177, 'NH', 'VU', '.vu', 'Vanuatu', 'وانواتو', 1, NULL, NULL),
(178, 'NI', 'NG', '.ng', 'Nigeria', 'نیجریه', 1, NULL, NULL),
(179, 'NL', 'NL', '.nl', 'Netherlands', 'هلند', 1, NULL, NULL),
(180, 'NM', '', '', 'No Man\'s Land', 'هیچ مردی زمین نیست', 1, NULL, NULL),
(181, 'NO', 'NO', '.no', 'Norway', 'نروژ', 1, NULL, NULL),
(182, 'NP', 'NP', '.np', 'Nepal', 'نپال', 1, NULL, NULL),
(183, 'NR', 'NR', '.nr', 'Nauru', 'نائورو', 1, NULL, NULL),
(184, 'NS', 'SR', '.sr', 'Suriname', 'سورینام', 1, NULL, NULL),
(185, 'NT', 'AN', '.an', 'Netherlands Antilles', 'آنتیل هلند', 1, NULL, NULL),
(186, 'NU', 'NI', '.ni', 'Nicaragua', 'نیکاراگوئه', 1, NULL, NULL),
(187, 'NZ', 'NZ', '.nz', 'New Zealand', 'نیوزلند', 1, NULL, NULL),
(188, 'PA', 'PY', '.py', 'Paraguay', 'پاراگوئه', 1, NULL, NULL),
(189, 'PC', 'PN', '.pn', 'Pitcairn Islands', 'جزایر پیتکرن', 1, NULL, NULL),
(190, 'PE', 'PE', '.pe', 'Peru', 'پرو', 1, NULL, NULL),
(191, 'PF', '-', '-', 'Paracel Islands', 'جزایر پاراسل', 1, NULL, NULL),
(192, 'PG', '-', '-', 'Spratly Islands', 'جزایر اسپارتلی', 1, NULL, NULL),
(193, 'PK', 'PK', '.pk', 'Pakistan', 'پاکستان', 1, NULL, NULL),
(194, 'PL', 'PL', '.pl', 'Poland', 'لهستان', 1, NULL, NULL),
(195, 'PM', 'PA', '.pa', 'Panama', 'پاناما', 1, NULL, NULL),
(196, 'PO', 'PT', '.pt', 'Portugal', 'کشور پرتغال', 1, NULL, NULL),
(197, 'PP', 'PG', '.pg', 'Papua New Guinea', 'پاپوآ گینه نو', 1, NULL, NULL),
(198, 'PS', 'PW', '.pw', 'Palau', 'پالائو', 1, NULL, NULL),
(199, 'PU', 'GW', '.gw', 'Guinea-Bissau', 'گینه بیسائو', 1, NULL, NULL),
(200, 'QA', 'QA', '.qa', 'Qatar', 'قطر', 1, NULL, NULL),
(201, 'RE', 'RE', '.re', 'Reunion', 'تجدید دیدار', 1, NULL, NULL),
(202, 'RI', 'RS', '.rs', 'Serbia', 'صربستان', 1, NULL, NULL),
(203, 'RM', 'MH', '.mh', 'Marshall Islands', 'جزایر مارشال', 1, NULL, NULL),
(204, 'RN', 'MF', '-', 'Saint Martin', 'سنت مارتین', 1, NULL, NULL),
(205, 'RO', 'RO', '.ro', 'Romania', 'رومانی', 1, NULL, NULL),
(206, 'RP', 'PH', '.ph', 'Philippines', 'فیلیپین', 1, NULL, NULL),
(207, 'RQ', 'PR', '.pr', 'Puerto Rico', 'پورتوریکو', 1, NULL, NULL),
(208, 'RS', 'RU', '.ru', 'Russia', 'روسیه', 1, NULL, NULL),
(209, 'RW', 'RW', '.rw', 'Rwanda', 'رواندا', 1, NULL, NULL),
(210, 'SA', 'SA', '.sa', 'Saudi Arabia', 'عربستان سعودی', 1, NULL, NULL),
(211, 'SB', 'PM', '.pm', 'Saint Pierre and Miquelon', 'سنت پیر و میکلون', 1, NULL, NULL),
(212, 'SC', 'KN', '.kn', 'Saint Kitts and Nevis', 'سنت کیتس و نویس', 1, NULL, NULL),
(213, 'SE', 'SC', '.sc', 'Seychelles', 'سیشل', 1, NULL, NULL),
(214, 'SF', 'ZA', '.za', 'South Africa', 'آفریقای جنوبی', 1, NULL, NULL),
(215, 'SG', 'SN', '.sn', 'Senegal', 'سنگال', 1, NULL, NULL),
(216, 'SH', 'SH', '.sh', 'Saint Helena', 'سنت هلن', 1, NULL, NULL),
(217, 'SI', 'SI', '.si', 'Slovenia', 'اسلوونی', 1, NULL, NULL),
(218, 'SL', 'SL', '.sl', 'Sierra Leone', 'سیرا لئون', 1, NULL, NULL),
(219, 'SM', 'SM', '.sm', 'San Marino', 'سان مارینو', 1, NULL, NULL),
(220, 'SN', 'SG', '.sg', 'Singapore', 'سنگاپور', 1, NULL, NULL),
(221, 'SO', 'SO', '.so', 'Somalia', 'سومالی', 1, NULL, NULL),
(222, 'SP', 'ES', '.es', 'Spain', 'اسپانیا', 1, NULL, NULL),
(223, 'ST', 'LC', '.lc', 'Saint Lucia', 'سنت لوسیا', 1, NULL, NULL),
(224, 'SU', 'SD', '.sd', 'Sudan', 'سودان', 1, NULL, NULL),
(225, 'SV', 'SJ', '.sj', 'Svalbard', 'اسباب بازی', 1, NULL, NULL),
(226, 'SW', 'SE', '.se', 'Sweden', 'سوئد', 1, NULL, NULL),
(227, 'SX', 'GS', '.gs', 'South Georgia and the Islands', 'جنوب گرجستان و جزایر', 1, NULL, NULL),
(228, 'SY', 'SY', '.sy', 'Syrian Arab Republic', 'جمهوری عربی سوریه', 1, NULL, NULL),
(229, 'SZ', 'CH', '.ch', 'Switzerland', 'سوئیس', 1, NULL, NULL),
(230, 'TD', 'TT', '.tt', 'Trinidad and Tobago', 'ترینیداد و توباگو', 1, NULL, NULL),
(231, 'TE', '-', '-', 'Tromelin Island', 'جزیره ترولین', 1, NULL, NULL),
(232, 'TH', 'TH', '.th', 'Thailand', 'تایلند', 1, NULL, NULL),
(233, 'TI', 'TJ', '.tj', 'Tajikistan', 'تاجیکستان', 1, NULL, NULL),
(234, 'TK', 'TC', '.tc', 'Turks and Caicos Islands', 'جزایر ترکس و کایکوس', 1, NULL, NULL),
(235, 'TL', 'TK', '.tk', 'Tokelau', 'توکلو', 1, NULL, NULL),
(236, 'TN', 'TO', '.to', 'Tonga', 'تونگا', 1, NULL, NULL),
(237, 'TO', 'TG', '.tg', 'Togo', 'رفتن', 1, NULL, NULL),
(238, 'TP', 'ST', '.st', 'Sao Tome and Principe', 'سائوتومه و پرنسیپه', 1, NULL, NULL),
(239, 'TS', 'TN', '.tn', 'Tunisia', 'تونس', 1, NULL, NULL),
(240, 'TT', 'TL', '.tl', 'East Timor', 'تیمور شرقی', 1, NULL, NULL),
(241, 'TU', 'TR', '.tr', 'Turkey', 'بوقلمون', 1, NULL, NULL),
(242, 'TV', 'TV', '.tv', 'Tuvalu', 'توووالو', 1, NULL, NULL),
(243, 'TW', 'TW', '.tw', 'Taiwan', 'تایوان', 1, NULL, NULL),
(244, 'TX', 'TM', '.tm', 'Turkmenistan', 'ترکمنستان', 1, NULL, NULL),
(245, 'TZ', 'TZ', '.tz', 'Tanzania, United Republic of', 'تانزانیا، جمهوری متحده', 1, NULL, NULL),
(246, 'UG', 'UG', '.ug', 'Uganda', 'اوگاندا', 1, NULL, NULL),
(247, 'UK', 'GB', '.uk', 'United Kingdom', 'انگلستان', 1, NULL, NULL),
(248, 'UP', 'UA', '.ua', 'Ukraine', 'اوکراین', 1, NULL, NULL),
(249, 'US', 'US', '.us', 'United States', 'ایالات متحده', 1, NULL, NULL),
(250, 'UV', 'BF', '.bf', 'Burkina Faso', 'بورکینافاسو', 1, NULL, NULL),
(251, 'UY', 'UY', '.uy', 'Uruguay', 'اروگوئه', 1, NULL, NULL),
(252, 'UZ', 'UZ', '.uz', 'Uzbekistan', 'ازبکستان', 1, NULL, NULL),
(253, 'VC', 'VC', '.vc', 'Saint Vincent and the Grenadines', 'سنت وینسنت و گرنادین', 1, NULL, NULL),
(254, 'VE', 'VE', '.ve', 'Venezuela', 'ونزوئلا', 1, NULL, NULL),
(255, 'VI', 'VG', '.vg', 'British Virgin Islands', 'جزایر ویرجین بریتانیا', 1, NULL, NULL),
(256, 'VM', 'VN', '.vn', 'Vietnam', 'ویتنام', 1, NULL, NULL),
(257, 'VQ', 'VI', '.vi', 'Virgin Islands (US)', 'جزایر ویرجین (ایالات متحده)', 1, NULL, NULL),
(258, 'VT', 'VA', '.va', 'Holy See (Vatican City)', 'مقدس (واتیکان)', 1, NULL, NULL),
(259, 'WA', 'NA', '.na', 'Namibia', 'نامیبیا', 1, NULL, NULL),
(260, 'WE', '-', '-', 'West Bank', 'بانک غرب', 1, NULL, NULL),
(261, 'WF', 'WF', '.wf', 'Wallis and Futuna', 'والیس و فوتونا', 1, NULL, NULL),
(262, 'WI', 'EH', '.eh', 'Western Sahara', 'صحرای غربی', 1, NULL, NULL),
(263, 'WQ', 'UM', '-', 'Wake Island', 'جزیره ویک', 1, NULL, NULL),
(264, 'WS', 'WS', '.ws', 'Samoa', 'ساموآ', 1, NULL, NULL),
(265, 'WZ', 'SZ', '.sz', 'Swaziland', 'سوازیلند', 1, NULL, NULL),
(266, 'YI', 'CS', '.yu', 'Serbia and Montenegro', 'صربستان و مونته نگرو', 1, NULL, NULL),
(267, 'YM', 'YE', '.ye', 'Yemen', 'یمن', 1, NULL, NULL),
(268, 'ZA', 'ZM', '.zm', 'Zambia', 'زامبیا', 1, NULL, NULL),
(269, 'ZI', 'ZW', '.zw', 'Zimbabwe', 'زیمبابوه', 1, NULL, NULL);